--Data Analysis Project Using SQL and Power BI � Analysis of Adidais USA Sales Dataset
--Source Data.world
--data set was importerd into sql server--
-- calling up my table --
Select * from DataSales_Adidas$;
--Total number of Transaction made
SELECT 
COUNT(*) as Total_transaction
INTO Number_transaction
From DataSales_Adidas$;

 -- Checking revenue generated by each Retailer
SELECT 
 DISTINCT Retailer,
 SUM(Total_Sales) As RevenuePer_Retailer
FROM
DataSales_Adidas$
GROUP BY
Retailer
ORDER BY
RevenuePer_Retailer desc;

 -- Checking revenue generated by each Retailer
SELECT Retailer, 
Sum(Total_Sales) as RevenuePer_Retailer
FROM DataSales_Adidas$
GROUP BY Retailer 
ORDER BY RevenuePer_Retailer desc;

--Sales regional performance 
SELECT Region,
       MAX(Total_Sales) AS max_Sales,
       MIN(Total_Sales) AS min_Sales
FROM [DataSales_Adidas$]
GROUP BY Region
ORDER BY max_Sales DESC;

-- Product performance
SELECT Product, 
SUM(Units_Sold) as Product_performance
FROM DataSales_Adidas$
GROUP BY Product
ORDER BY Product_Performance desc;

-- Best three performing product
SELECT
 TOP 3 Product,
 SUM(Units_Sold) As Quntity_Sold
FROM
DataSales_Adidas$
GROUP BY Product
ORDER BY Quntity_Sold DESC;

--Salse Mathod performance
SELECT  DISTINCT
 Sales_Method,
 COUNT( Sales_Method) as MethodOf_Puchase
FROM DataSales_Adidas$
GROUP BY Sales_Method
ORDER By MethodOf_Puchase ASC;

--product performance by city
SELECT  DISTINCT City,
Sum(Units_Sold) as TotalUnits_Sold,
Sum(Total_Sales) as TotalSales,
MAX(Product) as MAX_Product_Bought,
MIN(Product) as MIN_Product_Bought
FROM DataSales_Adidas$
GROUP BY City
ORDER BY  TotalSales DESC;
--Sorted the product line based on the highest of total purchasing--

SELECT
 DISTINCT Product,
 SUM(Units_Sold) as total_units
FROM DataSales_Adidas$
GROUP BY Product
ORDER BY total_units DESC;

Select * from DataSales_Adidas$;

--What is the total purchasing of each product line in every month?--

SELECT DISTINCT Product, 
    DATEPART(Month, Invoice_Date) as Month, 
    SUM(Units_Sold) as Quantity_purchased 
FROM DataSales_Adidas$ 
GROUP BY Product, DATEPART(Month, Invoice_Date) 
ORDER BY DATEPART(Month, Invoice_Date) asc;

--What is the total purchasing of each product line in every month?--

SELECT DISTINCT Product, 
    DATEPART(Year, Invoice_Date) as Year, 
    SUM(Units_Sold) as Quantity_purchased 
FROM DataSales_Adidas$ 
GROUP BY Product, DATEPART(Year, Invoice_Date) 
ORDER BY DATEPART(Year, Invoice_Date) DESC;

--States Where Units_sold is 65,000 and above

SELECT State, DATEPART(YEAR, Invoice_Date) as Year
INTO State_Unitsold
FROM DataSales_Adidas$
GROUP BY State, DATEPART(YEAR, Invoice_Date)
HAVING SUM(Units_Sold) >= 65000
ORDER BY State DESC;
-- Sort State by Revenue generated--

SELECT State,
  SUM(Total_Sales) AS State_Revenue,
  MIN(Total_Sales) AS Min_StateRevenue
FROM DataSales_Adidas$
GROUP BY State
ORDER BY Min_StateRevenue DESC;
